#!/bin/bash

cmake -S nyan-env/llvm-project/runtimes -B build-libcxx -G "Unix Makefiles" \
  --toolchain `pwd`/i686-elf.cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_RUNTIMES="libcxx" \
  -DLIBCXX_ENABLE_SHARED=OFF \
  -DLIBCXX_ENABLE_EXCEPTIONS=OFF \
  -DLIBCXX_ENABLE_RTTI=OFF \
  -DLIBCXX_ENABLE_FILESYSTEM=OFF \
  -DLIBCXX_ENABLE_RANDOM_DEVICE=OFF \
  -DLIBCXX_ENABLE_LOCALIZATION=OFF \
  -DLIBCXX_ENABLE_UNICODE=OFF \
  -DLIBCXX_HAS_TERMINAL_AVAILABLE=OFF \
  -DLIBCXX_ENABLE_WIDE_CHARACTERS=OFF \
  -DLIBCXX_ENABLE_THREADS=OFF \
  -DLIBCXX_ENABLE_MONOTONIC_CLOCK=OFF \
  -DLIBCXX_ENABLE_TIME_ZONE_DATABASE=OFF \
  -DLIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=OFF \
  -DLIBCXX_CXX_ABI=none \
  -DLIBCXX_HAS_MUSL_LIBC=ON

cmake --build build-libcxx -- -j 16
sudo cmake --install build-libcxx --prefix `pwd`/libcxx