#pragma once

#include <stdint.h>
#include <sys/types.h>

#include "../kernel/lib/result.hpp"

#define SYS_EPERM Errno{1}
#define SYS_ENOENT Errno{2}
#define SYS_ESRCH Errno{3}
#define SYS_EINTR Errno{4}
#define SYS_EIO Errno{5}
#define SYS_ENXIO Errno{6}
#define SYS_E2BIG Errno{7}
#define SYS_ENOEXEC Errno{8}
#define SYS_EBADF Errno{9}
#define SYS_ECHILD Errno{10}
#define SYS_EAGAIN Errno{11}
#define SYS_ENOMEM Errno{12}
#define SYS_EACCES Errno{13}
#define SYS_EFAULT Errno{14}
#define SYS_ENOTBLK Errno{15}
#define SYS_EBUSY Errno{16}
#define SYS_EEXIST Errno{17}
#define SYS_EXDEV Errno{18}
#define SYS_ENODEV Errno{19}
#define SYS_ENOTDIR Errno{20}
#define SYS_EISDIR Errno{21}
#define SYS_EINVAL Errno{22}
#define SYS_ENFILE Errno{23}
#define SYS_EMFILE Errno{24}
#define SYS_ENOTTY Errno{25}
#define SYS_ETXTBSY Errno{26}
#define SYS_EFBIG Errno{27}
#define SYS_ENOSPC Errno{28}
#define SYS_ESPIPE Errno{29}
#define SYS_EROFS Errno{30}
#define SYS_EMLINK Errno{31}
#define SYS_EPIPE Errno{32}
#define SYS_EDOM Errno{33}
#define SYS_ERANGE Errno{34}
#define SYS_EDEADLK Errno{35}
#define SYS_ENAMETOOLONG Errno{36}
#define SYS_ENOLCK Errno{37}
#define SYS_ENOSYS Errno{38}
#define SYS_ENOTEMPTY Errno{39}
#define SYS_ELOOP Errno{40}
#define SYS_EWOULDBLOCK Errno{11}
#define SYS_ENOMSG Errno{42}
#define SYS_EIDRM Errno{43}
#define SYS_ECHRNG Errno{44}
#define SYS_EL2NSYNC Errno{45}
#define SYS_EL3HLT Errno{46}
#define SYS_EL3RST Errno{47}
#define SYS_ELNRNG Errno{48}
#define SYS_EUNATCH Errno{49}
#define SYS_ENOCSI Errno{50}
#define SYS_EL2HLT Errno{51}
#define SYS_EBADE Errno{52}
#define SYS_EBADR Errno{53}
#define SYS_EXFULL Errno{54}
#define SYS_ENOANO Errno{55}
#define SYS_EBADRQC Errno{56}
#define SYS_EBADSLT Errno{57}
#define SYS_EDEADLOCK Errno{35}
#define SYS_EBFONT Errno{59}
#define SYS_ENOSTR Errno{60}
#define SYS_ENODATA Errno{61}
#define SYS_ETIME Errno{62}
#define SYS_ENOSR Errno{63}
#define SYS_ENONET Errno{64}
#define SYS_ENOPKG Errno{65}
#define SYS_EREMOTE Errno{66}
#define SYS_ENOLINK Errno{67}
#define SYS_EADV Errno{68}
#define SYS_ESRMNT Errno{69}
#define SYS_ECOMM Errno{70}
#define SYS_EPROTO Errno{71}
#define SYS_EMULTIHOP Errno{72}
#define SYS_EDOTDOT Errno{73}
#define SYS_EBADMSG Errno{74}
#define SYS_EOVERFLOW Errno{75}
#define SYS_ENOTUNIQ Errno{76}
#define SYS_EBADFD Errno{77}
#define SYS_EREMCHG Errno{78}
#define SYS_ELIBACC Errno{79}
#define SYS_ELIBBAD Errno{80}
#define SYS_ELIBSCN Errno{81}
#define SYS_ELIBMAX Errno{82}
#define SYS_ELIBEXEC Errno{83}
#define SYS_EILSEQ Errno{84}
#define SYS_ERESTART Errno{85}
#define SYS_ESTRPIPE Errno{86}
#define SYS_EUSERS Errno{87}
#define SYS_ENOTSOCK Errno{88}
#define SYS_EDESTADDRREQ Errno{89}
#define SYS_EMSGSIZE Errno{90}
#define SYS_EPROTOTYPE Errno{91}
#define SYS_ENOPROTOOPT Errno{92}
#define SYS_EPROTONOSUPPORT Errno{93}
#define SYS_ESOCKTNOSUPPORT Errno{94}
#define SYS_EOPNOTSUPP Errno{95}
#define SYS_EPFNOSUPPORT Errno{96}
#define SYS_EAFNOSUPPORT Errno{97}
#define SYS_EADDRINUSE Errno{98}
#define SYS_EADDRNOTAVAIL Errno{99}
#define SYS_ENETDOWN Errno{100}
#define SYS_ENETUNREACH Errno{101}
#define SYS_ENETRESET Errno{102}
#define SYS_ECONNABORTED Errno{103}
#define SYS_ECONNRESET Errno{104}
#define SYS_ENOBUFS Errno{105}
#define SYS_EISCONN Errno{106}
#define SYS_ENOTCONN Errno{107}
#define SYS_ESHUTDOWN Errno{108}
#define SYS_ETOOMANYREFS Errno{109}
#define SYS_ETIMEDOUT Errno{110}
#define SYS_ECONNREFUSED Errno{111}
#define SYS_EHOSTDOWN Errno{112}
#define SYS_EHOSTUNREACH Errno{113}
#define SYS_EALREADY Errno{114}
#define SYS_EINPROGRESS Errno{115}
#define SYS_ESTALE Errno{116}
#define SYS_EUCLEAN Errno{117}
#define SYS_ENOTNAM Errno{118}
#define SYS_ENAVAIL Errno{119}
#define SYS_EISNAM Errno{120}
#define SYS_EREMOTEIO Errno{121}
#define SYS_EDQUOT Errno{122}
#define SYS_ENOMEDIUM Errno{123}
#define SYS_EMEDIUMTYPE Errno{124}
#define SYS_ECANCELED Errno{125}
#define SYS_ENOKEY Errno{126}
#define SYS_EKEYEXPIRED Errno{127}
#define SYS_EKEYREVOKED Errno{128}
#define SYS_EKEYREJECTED Errno{129}
#define SYS_EOWNERDEAD Errno{130}
#define SYS_ENOTRECOVERABLE Errno{131}
#define SYS_ERFKILL Errno{132}
#define SYS_EHWPOISON Errno{133}
#define SYS_ENOTSUP Errno{95}
